CREATE SEQUENCE seq_raw_sales START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_stg_sales START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_clean_sales START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_etl_log START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_etl_error_log START WITH 1 INCREMENT BY 1;